import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const apiSlice = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: '/mainApi' }),
  tagTypes: ['Race'],
  endpoints: (builder) => ({
    getRaces: builder.query({
      query: () => ({ url: '/races', method: 'GET', body: {} }),
    }),
  }),
});

export const {
  useGetRacesQuery, // autoGenerated hooks use + ${endpointName} + ${TypeOfEndpoint}(Query or Mutation)
} = apiSlice;
